### ISSUE TITLE
Not compatible with Apple Music Radio Stations

### ISSUE THREAD

**Issue by crivera2712** [cbyrne/Playing#4]
If you go and play a radio with custom tags enabled, it will send you to safe mode. If you have another tweak like RoadRunner and you exit Safe Mode while still playing music, it will send you back to safe mode. 

Device info:
`iPhone XS, iOS 13.5, unc0ver 5.0.1`

Tweak version:
`1.1.1 `

Crash log: [Crash Log](https://pastebin.com/4c6DMPcb)

**Comment by conorthedev** [comment]
Thanks for the report, I'll look into this soon

**Comment by conorthedev** [comment]
Just fixed this in 3038230
